name: Lint GitHub Actions workflows
on: push

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Check workflow files
        uses: docker://rhysd/actionlint@sha256:02ccb6d91e4cb4a7b21eb99d5274d257e81ae667688d730e89d7ea0d6d35db91
        with:
          args: -color
